### PR TITLE
Go 117 dependency update

### PR DESCRIPTION
**Pull request by LJ-Software**
# Description
Updated the go version of this module to 1.17 and updated the version of all of the module dependencies to latest.

All of the otel modules were updated to newer versions bringing with it many changes in the code to accommodate. Most of the changes are method & attribute name changes in the otel libraries.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| N/A |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?

- [x] End to End integration test with Observability
```
--- PASS: Test_Query_Topology (14.17s)
PASS
ok      karavi-testing/karavi-topology/topology-test    14.197s
```

### CODE REVIEW

**Review by alikdell — APPROVED** [review]

**Review by hoppea2 — COMMENTED** [review]
check failures on vetting and unit test actions

**Comment by LJ-Software** [comment]
run e2e test

**Comment by LJ-Software** [comment]
run e2e test

**Comment by LJ-Software** [comment]
run e2e test

**Comment by alikdell** [comment]
e2e pass

**Review by alikdell — APPROVED** [review]

**Review by atye — APPROVED** [review]

**Review by hoppea2 — APPROVED** [review]

**Pull request merged**
