### PR TITLE
Update docs to fix non-inclusive language use

### PR DESCRIPTION
**Pull request by ameer-jabbar**
# Description

Updating the documentation to remove some non-inclusive word usage.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|     #61       |

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run 'make check' to ensure my code does not have any formatting, vetting, linting, or security issues
- [ ] I have run 'make test' to ensure new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degrade
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

Documentation change only.

### CODE REVIEW

**Comment by ameer-jabbar** [comment]
Run e2e test

**Review by AronAtDell — APPROVED** [review]
Looks good. Thanks!

**Review by AronAtDell — APPROVED** [review]
Looks good. Thanks!

**Review by atye — APPROVED** [review]

**Review by alikdell — APPROVED** [review]

**Comment by ameer-jabbar** [comment]
Skip ci

**Comment by ameer-jabbar** [comment]
Run e2e test

**Pull request merged**
