### PR TITLE
add support for PowerScale topology

### PR DESCRIPTION
**Pull request by YianZong**
# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/334 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have inspected the Grafana dashboards to verify the data is displayed properly
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Test A: UT
image

- [x] Test B: manual testing
image

# Manual inspection of the GUI
I have verified that the dashboards show the data properly while generating I/O and storage resources

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by atye** [comment]
Can one of the admins verify this patch?

**Review by hoppea2 — DISMISSED** [review]
Hi Yian, please hold off on merging any PRs to the main branch until after CSM 1.3 release (06/21)

**Comment by YianZong** [comment]
> Hi Yian, please hold off on merging any PRs to the main branch until after CSM 1.3 release (06/21)

Sure, @hoppea2

**Comment by YianZong** [comment]
Hi @hoppea2 , can we resume PR review and merge for Q3 features now?

**Review by taohe1012 — DISMISSED** [review]

**Review by forrestxia — APPROVED** [review]

**Review by sharmilarama — APPROVED** [review]
LGTM

**Comment by sharmilarama** [comment]
run e2e test

**Review by forrestxia — APPROVED** [review]

**Review by taohe1012 — APPROVED** [review]

**Review by baoy1 — APPROVED** [review]

**Comment by YianZong** [comment]
Hi code owners, please kindly review and approve this PR. Thank you!

**Pull request merged**
