### PR TITLE
Adding vxflexos csi-driver version 1.2.1 to supported versions

### PR DESCRIPTION
**Pull request by hoppea2**
# Description

Adding VxFlexOS CSI Driver 1.2.1 to the list of qualified drivers.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|      #33     |

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have run 'make check' to ensure my code does not have any formatting, vetting, linting, or security issues
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by alikdell — APPROVED** [review]

**Review by tdawe — APPROVED** [review]

**Review by gallacher — APPROVED** [review]

**Comment by ameer-jabbar** [comment]
e2e pass

**Comment by ameer-jabbar** [comment]
e2e pass

**Comment by ameer-jabbar** [comment]
e2e pass

**Comment by ameer-jabbar** [comment]
e2e pass

**Pull request merged**
