### PR TITLE
Update mockgen to latest in GitHub action

### PR DESCRIPTION
**Pull request by chimanjain**
# Description
Update mockgen to latest in GitHub action

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Successful GitHub action run

### CODE REVIEW

**Review by donatwork — DISMISSED** [review]

**Comment by AronAtDell** [comment]
@chimanjain - What is the linting error? Is it addressed? Thanks!

**Comment by donatwork** [comment]
> @chimanjain - What is the linting error? Is it addressed? Thanks!

Two days ago a new version of golangci-lint was released, 1.60.1. This added a new check and flags the way we were logging. In some older code the call to fmt.Errorf uses a function to return the format parameters. It is in a few other drivers as well. The previous version of the linter did not flag this.

**Comment by AronAtDell** [comment]
@donatwork - so we fixed the latest flagged issue with linting?

**Comment by donatwork** [comment]
The repo has v4 of the linter action. There is v5 which would have failed the PR build. Chiman, could you please also update to v5 of the linter?

uses: golangci/golangci-lint-action@**v5**

**Comment by chimanjain** [comment]
Thanks @AronAtDell and @donatwork for pointing the linting error. Previously I checked whether all the github action ran successfully and even the github action for golangci lint was successful, It was missed from my part. Updated the golangci-lint-action to `v5`.

**Review by donatwork — APPROVED** [review]

**Comment by AronAtDell** [comment]
@chimanjain - Thanks! I saw that the actions all passed previously. The good thing is that we did not ignore the issues in the PR and you addressed them.  Appreciate your help and attention to these details. Have a good weekend! Thanks @donatwork !

**Review by AronAtDell — APPROVED** [review]

**Pull request merged**
