### PR TITLE
Removed -quiet arg from gosec action

### PR DESCRIPTION
**Pull request by gallacher**
# Description

Remvoe the -quiet arg from the gosec action to avoid suppressing security errors 

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|    https://github.com/dell/karavi-observability/issues/38      |

# Checklist

- [x] I have performed a self-review of my own code

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] GitHub checks have validated the change

### CODE REVIEW

**Comment by ioeicicdsvc** [comment]
@gallacher: Thank you for submitting your pull request!

Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by gallacher** [comment]
run e2e test

**Review by hoppea2 — APPROVED** [review]

**Comment by gallacher** [comment]
skip e2e

**Comment by gallacher** [comment]
e2e pass

**Review by ameer-jabbar — APPROVED** [review]

**Pull request merged**
