### PR TITLE
add support for powermax topology

### PR DESCRIPTION
**Pull request by YianZong**
# Description
add support for powermax topology

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/586 |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [X] I have not allowed coverage numbers to degenerate
- [X] I have maintained at least 90% code coverage
- [X] I have inspected the Grafana dashboards to verify the data is displayed properly
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [X] UT
image

- [X] Manual
image

# Manual inspection of the GUI
I have verified that the dashboards show the data properly while generating I/O and storage resources

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by YianZong** [comment]
run e2e test

**Comment by forrestxia** [comment]
run e2e test

**Review by baoy1 — APPROVED** [review]

**Comment by forrestxia** [comment]
run e2e test

**Comment by forrestxia** [comment]
run e2e test

**Review by forrestxia — APPROVED** [review]

**Pull request merged**
